@INCLUDE main.conf
@INCLUDE ../../input/dummy.conf
@INCLUDE ../../output/dummy.conf
#TODO: Fix permissions issue
#@INCLUDE ../../input/docker.conf
#@INCLUDE ../../output/docker.conf
@INCLUDE ../../output/loki.conf
