[INPUT]
    Name stdin
    Tag dummy_stdout
    # Parser to capture input in other format
    # Supported formats:
    # JSON, 
    # 2 element JSON array in Fluent Bit event format ([TIMESTAMP, { "key": "value" }])
    # [[TIMESTAMP, METADATA], { "key": "value" }] (from 2.10)
    Parser stringify_message

[INPUT]
    Name Dummy
    Tag srv_dummy_stage
    dummy { "hello": "world" }

[INPUT]
    Name Dummy
    Tag srv_dummy1_stage
    dummy { "more": "stuff" }

[INPUT]
    Name disk
    Interval_Sec 5
    Tag wsl_disk

[INPUT]
    Name cpu
    #Interval_Sec 5
    Interval_NSec 150000 # Set interval to 1.5 as nano seconds
    #Pid Monitor a given process 
    tag wsl_cpu

[INPUT]
    Name mem
    Interval_Sec 5
    Tag wsl_memory

[INPUT]
    Name netif
    Interface eth0
    Interval_Sec 5
    Tag wsl_network

[INPUT]
    Name tail
    Alias containers_log
    Tag containers
    Path '/var/log/containers/*.log'
    Read_From_Head True
    Buffer_Chunk_Size 128kb
    Buffer_Max_Size 128kb
