[SERVICE]
    Flush 1
    Daemon Off
    Log_Level info

[INPUT]
    Name Dummy
    Tag srv_dummy_stage
    dummy { "hello": "world" }

[INPUT]
    Name Dummy
    Tag srv_dummy1_stage
    dummy { "more": "stuff" }
    
[OUTPUT]
    Name stdout
    Match *

[OUTPUT]
    Name stdout
    Format json
    Match *
    Json_Date_Format iso8601 
